### Site metadata ###

title: My GitHub Projects

repository: MichaelCurrin/my-github-projects
author: Michael Currin
twitter_handle: MichaelCurrin

### Build settings ###

url: https://michael-currin.netlify.app
baseurl: ""

theme: jekyll-bulma

permalink: pretty

header_pages:
  - repos.md
  - topics.md
  - about.md

collections:
  topics:
    output: true

liquid:
  strict_filters: true

exclude:
  - docs/
  - LICENSE
  - README.md
  - Makefile
  - netlify.toml
  - package.json
  - package-lock.json
